function c = anatomy(m);

% ColEdit function [cmap] = anatomy(maplength);
%
% colormap m-file written by ColEdit
% version 1.1 on 04-Nov-2002
%
% input  :	[maplength]	[64]	- colormap length
%
% output :	cmap			- colormap RGB-value array
  
  if nargin<1, m = size(get(gcf,'colormap'),1); end

  % set red points
  r = [ [];...
        [0 0];...
        [0.075 0];...
        [0.375 0.3];...
        [0.625 1];...
        [1 1];...
        [] ];
  
  % set green points
  g = [ [];...
        [0 0];...
        [0.375 0.3];...
        [0.625 0.3];...
        [1 1];...
        [] ];
  
  % set blue points
  b = [ [];...
        [0 0];...
        [0.075 0.35];...
        [0.500 1];...
        [0.625 0];...
        [1 0.6];...
        [] ];
  % ColEditInfoEnd
  
  % interpolate colormap
  n = linspace(0,1,m);
  r = interp1(r(:,1),r(:,2),n,'linear');
  g = interp1(g(:,1),g(:,2),n,'linear');
  b = interp1(b(:,1),b(:,2),n,'linear');
  
  % compose colormap
  c = [r(:),g(:),b(:)];
