function DisplayConsole(hfig,data,lowhigh)
  
  displims = double([min(data(:)),max(data(:))]);
  if isempty(lowhigh), lowhigh = displims; end
  maxval = size(data);
  bcolor = 0.5*[1 1 1];
  fcolor = [1,0.8431,0];
  
  uipos = get(hfig,'Position');
  uipos = [10 10 200 uipos(4)-20];
  h1 = uipanel(...
      'Units','pixels',...
      'Position',uipos,...
      'BackgroundColor',bcolor,...
      'BorderType','none',...
      'BorderWidth',2,...
      'Tag','ConsolePanel');
  
  % Check boxes
  uipos = [1/20 1-1/4+2/90 1-1/10,1/4-3/90];
  h2 = uipanel(...
      'Parent',h1,...
      'Position',uipos,...
      'Title','Options',...
      'FontWeight','bold',...
      'ForegroundColor',fcolor,...
      'BackgroundColor',bcolor,...
      'BorderType','etchedin',...
      'BorderWidth',1);
  
  uipos = [1/20 1/20 2/5 1/5];
  uicontrol(...
      'Parent',h2,...
      'Units','normalized',...
      'BackgroundColor',bcolor,...
      'ForegroundColor',[1 1 1],...
      'Callback',@UpdateDisplay,...
      'Position',uipos,...
      'Style','checkbox',...
      'Value',0,...
      'Enable','off',...
      'String','Smooth',...
      'Tag','Smooth');
  
  uipos(2) = uipos(2)+1/5;
  uicontrol(...
      'Parent',h2,...
      'Units','normalized',...
      'BackgroundColor',bcolor,...
      'ForegroundColor',[1 1 1],...
      'Position',uipos,...
      'Style','checkbox',...
      'Enable','off',...
      'String','Coronal',...
      'Tag','Coronal');
  
  uipos(2) = uipos(2)+1/5;
  %uipos(1) = uipos(1)+1/2;
  uicontrol(...
      'Parent',h2,...
      'Units','normalized',...
      'BackgroundColor',bcolor,...
      'ForegroundColor',[1 1 1],...
      'Position',uipos,...
      'Style','checkbox',...
      'Enable','off',...
      'String','Sagittal',...
      'Tag','Sagittal');
  
  uipos = uipos+[0 1/5 2/5 0];
  %uipos = uipos+[-1/2 1/5 2/5 0];
  hpnt = uicontrol(...
      'Parent',h2,...
      'Units','normalized',...
      'BackgroundColor',bcolor,...
      'ForegroundColor',[1 1 1],...
      'Callback',@ShowPointCallback,...
      'Position',uipos,...
      'Style','checkbox',...
      'Enable','off',...
      'Value',0,...
      'String','Point',...
      'Tag','ShowPoint');
  
  % Graylevel adjustments
  uipos = [1/20 1/2+1/180 1-1/10,1/4];
  h3 = uipanel(...
      'Parent',h1,...
      'Position',uipos,...
      'Title','Intensity',...
      'FontWeight','bold',...
      'ForegroundColor',fcolor,...
      'BackgroundColor',bcolor,...
      'BorderType','etchedin',...
      'BorderWidth',1);
  
  uipos = [1/20 1/13 9/30 1/8];
  uicontrol(...
      'Parent',h3,...
      'Units','normalized',...
      'Callback',{@DispMinusCallback},...
      'Position',uipos,...
      'String','-');
  
  uipos(1) = uipos(1)+uipos(3);
  uicontrol(...
      'Parent',h3,...
      'Units','normalized',...
      'Callback',{@DispPlusCallback},...
      'Position',uipos,...
      'String','+');
  
  uipos(1) = uipos(1)+uipos(3);
  uicontrol(...
      'Parent',h3,...
      'Units','normalized',...
      'Callback',{@DispResetCallback},...
      'Position',uipos,...
      'String','*');

  uipos = [1/20 uipos(2)+1/6+1/90 3*uipos(3) 1/10];
  uicontrol(...
      'Parent',h3,...
      'BackgroundColor',0.6*[1 1 1],...
      'Units','normalized',...
      'Callback',{@DispWinCallback},...
      'Position',uipos,...
      'String','high',...
      'Style','slider',...
      'SliderStep',[0.005,0.05],...
      'Value',lowhigh(2),...
      'Min',displims(1),...
      'Max',displims(2),...
      'UserData',displims,...
      'Tag','Range');

  uipos(2) = uipos(2)+1/10;
  uicontrol(...
      'Parent',h3,...
      'BackgroundColor',0.3*[1 1 1],...
      'Units','normalized',...
      'Callback',{@DispWinCallback},...
      'Position',uipos,...
      'String','low',...
      'Style','slider',...
      'SliderStep',[0.005,0.05],...
      'Value',lowhigh(1),...
      'Min',displims(1),...
      'Max',displims(2),...
      'Tag','Range',...
      'UserData',displims);

  uipos(2) = uipos(2)+1/8;
  uipos(4) = 1/7.5;
  uicontrol(...
      'Parent',h3,...
      'Units','normalized',...
      'BackgroundColor','w',...
      'HorizontalAlignment','right',...
      'Callback',{@EditLimitCallback,2},...
      'Position',uipos+[9/20 0 -9/20 0],...
      'String',num2str(lowhigh(2)),...
      'Style','edit',...
      'Tag','RangeText');
  
  uicontrol(...
      'Parent',h3,...
      'Units','normalized',...
      'BackgroundColor','w',...
      'HorizontalAlignment','left',...
      'Callback',{@EditLimitCallback,1},...
      'Position',uipos+[0 0 -9/20 0],...
      'String',num2str(lowhigh(1)),...
      'Style','edit',...
      'Tag','RangeText');

  uipos(2) = uipos(2)+1/6;
  uipos(3) = 2/5-2/90;
  uicontrol(...
      'Parent',h3,...
      'Units','normalized',...
      'ForegroundColor','w',...
      'BackgroundColor',bcolor,...
      'HorizontalAlignment','left',...
      'Position',uipos,...
      'String','Colormap: ',...
      'Style','text');

  uipos = uipos+[uipos(3),3/90,1/8+1/90,0];
  uicontrol(...
      'Parent',h3,...
      'Units','normalized',...
      'BackgroundColor','w',...
      'Position',uipos,...
      'Style','popup',...
      'Value',3,...
      'String','Brain|Bone|Gray|Hot Metal|Rainbow|Spectral',...
      'Callback',@SetColormapCallback);

  if ndims(data)==2
    axes(...
        'Parent',h1,...
        'Units','normalized',...
        'Position',[0 0 3/4 1/2-3/90],...
        'Visible','off',...
        'Tag','ColorBar');
    %colorbar('north','XTickLabel',{});
    colorbar; %('YTickLabel',[lowhigh(1),lowhigh(2)]);
    return;
  end
  
  set(hpnt,'Value',1,'Enable','on');
  
  uipos = [1/20 1/90 1-1/10,1/2-2/90];
  h4 = uipanel(...
      'Parent',h1,...
      'Position',uipos,...
      'Title','Position',...
      'FontWeight','bold',...
      'ForegroundColor',fcolor,...
      'BackgroundColor',bcolor,...
      'BorderType','etchedin',...
      'BorderWidth',1);
  
  % Point sliders
  uipos = [1/20+18/30 1/20 9/30 1/15];
  uicontrol(...
      'Parent',h4,...
      'Units','normalized',...
      'BackgroundColor','w',...
      'HorizontalAlignment','right',...
      'Callback',{@EditPointCallback,3},...
      'Position',uipos,...
      'String',num2str(maxval(3)/2),...
      'Style','edit',...
      'Tag','PointText');

  uipos(1) = uipos(1)-9/30;
  uicontrol(...
      'Parent',h4,...
      'Units','normalized',...
      'BackgroundColor','w',...
      'HorizontalAlignment','right',...
      'Callback',{@EditPointCallback,2},...
      'Position',uipos,...
      'String',num2str(maxval(2)/2),...
      'Style','edit',...
      'Tag','PointText');

  uipos(1) = uipos(1)-9/30;
  uicontrol(...
      'Parent',h4,...
      'Units','normalized',...
      'BackgroundColor','w',...
      'HorizontalAlignment','right',...
      'Callback',{@EditPointCallback,1},...
      'Position',uipos,...
      'String',num2str(maxval(1)/2),...
      'Style','edit',...
      'Tag','PointText');

  uipos = [uipos(1)+22/30 uipos(2)+1/10, 1/12, 15/20]; 
  uicontrol(...
      'Parent',h4,...
      'BackgroundColor','r',...
      'Units','normalized',...
      'Callback',@UpdateDisplay,...
      'Position',uipos,...
      'String','zcoord',...
      'Style','slider',...
      'SliderStep',[1,10]/maxval(3),...
      'Value',maxval(3)/2,...
      'Min',1,...
      'Max',maxval(3),...
      'Tag','Point');

  uipos(1) = uipos(1)-9/30;
  uicontrol(...
      'Parent',h4,...
      'BackgroundColor','g',...
      'Units','normalized',...
      'Callback',@UpdateDisplay,...
      'Position',uipos,...
      'String','ycoord',...
      'Style','slider',...
      'SliderStep',[1,10]/maxval(1),...
      'Value',maxval(1)/2,...
      'Min',1,...
      'Max',maxval(1),...
      'Tag','Point');

  uipos(1) = uipos(1)-9/30;
  uicontrol(...
      'Parent',h4,...
      'BackgroundColor','b',...
      'Unit','normalized',...
      'Callback',@UpdateDisplay,...
      'Position',uipos,...
      'String','xcoord',...
      'Style','slider',...
      'SliderStep',[1,10]/maxval(2),...
      'Value',maxval(2)/2,...
      'Min',1,...
      'Max',maxval(2),...
      'Tag','Point');

  uipos = [1/25 uipos(2) 1/10 1/18];
  uicontrol(...
      'Parent',h4,...
      'Units','normalized',...
      'ForegroundColor','w',...
      'BackgroundColor',bcolor,...
      'HorizontalAlignment','right',...
      'Position',uipos,...
      'String','X',...
      'Style','text');

  uipos(1) = uipos(1)+9/30;
  uicontrol(...
      'Parent',h4,...
      'Units','normalized',...
      'ForegroundColor','w',...
      'BackgroundColor',bcolor,...
      'HorizontalAlignment','right',...
      'Position',uipos,...
      'String','Y',...
      'Style','text');

  uipos(1) = uipos(1)+9/30;
  uicontrol(...
      'Parent',h4,...
      'Units','normalized',...
      'ForegroundColor','w',...
      'BackgroundColor',bcolor,...
      'HorizontalAlignment','right',...
      'Position',uipos,...
      'String','Z',...
      'Style','text');


% --------------------------------------------------------------------
function EditLimitCallback(hobj,evdt,indx)
  
  handles = guidata(hobj);
  set(handles.Range(indx),'Value',str2num(get(hobj,'String')));
  UpdateDisplay(hobj,evdt);
  

% --------------------------------------------------------------------
function EditPointCallback(hobj,evdt,indx)
  
  handles = guidata(hobj);
  set(handles.Point(indx),'Value',str2num(get(hobj,'String')));
  UpdateDisplay(hobj,evdt);
  

% --------------------------------------------------------------------
function DispWinCallback(hobj,evdt)
  
  handles = guidata(hobj);
  lowhigh = get(handles.Range,'Value');
  set(handles.RangeText,{'String'},{num2str(lowhigh{1});num2str(lowhigh{2})});
  UpdateDisplay(hobj,evdt);
  

% --------------------------------------------------------------------
function DispMinusCallback(hobj,evdt)
  
  handles = guidata(hobj);
  lowhigh = cell2mat(get(handles.Range,'Value'));
  [low,high] = deal(min(lowhigh),max(lowhigh));
  set(handles.Range,'Min',low);
  set(handles.Range,'Max',high);
  

% --------------------------------------------------------------------
function DispPlusCallback(hobj,evdt)
  
  handles = guidata(hobj);
  lowhigh = cell2mat(get(handles.Range,'Value'));
  range = get(handles.Range(1),'UserData');
  extent = diff(lowhigh)*10;
  low = max(lowhigh(1)-extent,range(1));
  high = min(lowhigh(2)+extent,range(2));
  [low,high] = deal(min(low,high),max(low,high));
  set(handles.Range,'Min',low);
  set(handles.Range,'Max',high);
  

% --------------------------------------------------------------------
function DispResetCallback(hobj,evdt)
  
  handles = guidata(hobj);
  range = get(handles.Range(1),'UserData');
  set(handles.Range,'Min',range(1));
  set(handles.Range,'Max',range(2));
  set(handles.Range,{'Value'},{range(1);range(2)});
  set(handles.RangeText,{'String'},{num2str(range(1));num2str(range(2))});
  UpdateDisplay(hobj,evdt);
  

% --------------------------------------------------------------------
function SetColormapCallback(hobj,evdt)
  
  value = get(hobj,'Value');
  switch value
   case 1
    colormap(brain);
   case 2
    colormap(bone);
   case 3
    colormap(gray);
   case 4
    colormap(hotmetal);
   case 5
    colormap(rainbow);
   case 6
    colormap(spectral);
  end
  UpdateDisplay(hobj,evdt);
  
  
% --------------------------------------------------------------------
function ShowPointCallback(hobj,evdt)
  
  handles = guidata(hobj);
  if get(hobj,'Value')
    set(handles.ImageLine,'Visible','on');
  else
    set(handles.ImageLine,'Visible','off');
  end
  